### ISSUE TITLE
フロントエンドのdeployをmasterにマージしたときのみにしたい

### ISSUE THREAD

**Issue by tatara-takumi** [jphacks/F_2203#16]
## やること
今はpushするたびにbranchとか関係なくされてるっぽい

**Comment by putcho01** [comment]
デプロイ自体は、PR出した時のみ設定した！
今pushの度に動いてるやつは、eslintやtype checkが問題ないか確認してるだけなはず？

**Comment by tatara-takumi** [comment]
development取り込んだらvercelのデプロイしなくなった！
閉じます

**Comment by putcho01** [comment]
yarn run buildコマンド消してみた。
