### ISSUE TITLE
[sign_up, loginページ]ログインしてる場合は/:id ページに遷移するようにする

### ISSUE THREAD

**Issue by putcho01** [jphacks/F_2203#23]
## やること

- [ ] sign_upページでログインしてるかつ、DBにユーザーが存在する場合は/:id ページに遷移するようにする
- [ ] loginページでログインしてるかつ、DBにユーザーが存在する場合は/:id ページに遷移するようにする

**Comment by tatara-takumi** [comment]
実装済み
https://github.com/jphacks/F_2203/pull/32
