### ISSUE TITLE
ユーザー登録時のuserIdバリデーションチェック

### ISSUE THREAD

**Issue by putcho01** [jphacks/F_2203#34]
## やること
- すでに登録されているuserIdの場合にエラーを表示させる
- /newや/sign_upなどのページと重複するIdも登録不可にする

**Comment by tatara-takumi** [comment]
重複チェックってリアルタイム？それともはじめるボタン押したときのみチェックする？

**Comment by putcho01** [comment]
@tatara-takumi どうしようか？リアルタイムの方がUXは良さそうだけれど、実装大変になりそうなら始めるボタン押した時だけでも全然いいとは思う。おまかせします！🙏🏻

他のフィールドのバリデーションも、ボタン押した時にエラー表示されるようになってるので！

**Comment by tatara-takumi** [comment]
> /newや/sign_upなどのページと重複するIdも登録不可にする

これってどういう意味？
custom_idがpost.idと被らないようにってこと？

**Comment by putcho01** [comment]
@tatara-takumi 
 プロフィールページのパスが /:idだから、newとかloginのidで登録されると既存のページと被っちゃうなと思って。

**Comment by putcho01** [comment]
プロフィールページのパスをprofile/:idにする方が無難かな？

**Comment by tatara-takumi** [comment]
プロフィールページ以外のパスが/posts/:idとか/artist/:idとかなら被らなくない？

**Comment by putcho01** [comment]
だから、new, login, sign_up, などもバリデーションで弾けるようにしたい。

もしくは、プロフィールページのパスを/profile/:idに変更する。これだと、例えばnewで登録されても/profile/newになるから被らない。

**Comment by tatara-takumi** [comment]
あ、そういうことね！
確かにめんどいね。
/profile/:idに変更しちゃいますか
