### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by putcho01** [jphacks/F_2203#4]
## やること
DB設計する。
https://dbdiagram.io/home

コードはgit管理する。
rootディレクトリに`/document`フォルダを作成してその中に保存。

**Comment by putcho01** [comment]
Usersテーブルのidは、Firebase AuthenticationのUser UIDにして紐付けたい

**Comment by tatara-takumi** [comment]
https://dbdiagram.io/d/634a7f0ef0018a1c5f0c8339
