### ISSUE TITLE
プロフィール画像アップロード

### ISSUE THREAD

**Issue by putcho01** [jphacks/F_2203#45]
## やること
ユーザー登録時にプロフィール画像をfirestoreにアップロードする

1. プロフィール画像アップロード
2. アップロードが完了したら画像urlとユーザーの入力したデータを合わせてUserテーブルに追加。
3. ユーザー登録完了

の流れ。
## 備考
[できれば]
uriのパスをuidで固定したい。(`<storage url> / avatar /<uid>`みたいなイメージ ) 
固定することで、プロフィール画像編集時に、そのパスのファイルが置き換わるようにしたい。
以前登録したファイルをストレージに残し続けたくないから。

新しくissue切って、別スコープでもok

**Comment by putcho01** [comment]
https://zenn.dev/tiwu_dev/articles/72f8d7de22b164

**Comment by tatara-takumi** [comment]
firebase storage使うの確定でいい？

**Comment by putcho01** [comment]
@tatara-takumi なんでもいいよ！
firabaseすでに設定してあるから、firebase storageが一番実装が楽かなと思ってそれにしてるけれど、他にいいのあればそれでもok

**Comment by putcho01** [comment]
概要の説明アップデートしました。(詳しく書いた)

**Comment by tatara-takumi** [comment]
ありがとう

**Comment by tatara-takumi** [comment]
備考のパス固定は実際にしたことあるけど、何かしらの対策しないとキャッシュが更新されるまでずっと同じプロフィール画像になる。（対策は良く分かってない）
スマホアプリでやったときは、基本更新されなかった覚えがある。

**Comment by putcho01** [comment]
なるほど、、、。
そしたらパス指定は別タスクていいかも
